// This file been auto generated by the superbuild pipeline and the QuakeToC tool.
// Please do NOT modify this file. Instead please open the .qc files, and make changes there.
// This auto generated file is released under the GPL license, please see code_license.txt
// 

#pragma once

typedef enum {
	WEAPON_NONE,
	WEAPON_MIGHTYFOOT,
	WEAPON_PISTOL,
	WEAPON_RPG,
	WEAPON_SHOTGUN,
	NUM_WEAPONS,
} weapon_t;

__forceinline int BG_GetAddTimeForWeapon( int weaponNum ) {
	switch( weaponNum ) {
		 case WEAPON_MIGHTYFOOT: return 400;
		 case WEAPON_PISTOL: return 300;
		 case WEAPON_RPG: return 300;
		 case WEAPON_SHOTGUN: return 600;
	}
	return 0;
}
